version: '3.8'
services:

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    network_mode: bridge
    expose:
      - 80
    volumes:
      - .:/etc/nginx/
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=www.pre-angel.com,pre-angel.com,venture-sprint.com,www.venture-sprint.com,bot5.club,www.bot5.club,wechaty.js.org,localtunnel.chatie.io
      - LETSENCRYPT_HOST=www.pre-angel.com,pre-angel.com,venture-sprint.com,www.venture-sprint.com,bot5.club,www.bot5.club,wechaty.js.org,localtunnel.chatie.io
